### ISSUE TITLE
特殊字符造成目录生成出错

### ISSUE THREAD

**Issue by wangzilaing** [HiDeoo/starlight-obsidian#14]
### Describe the bug

md文件名中包含'%'，会造成生成目录错误。

### To Reproduce

PS C:\wa\vm\astro\MdDoc> npm run dev

> mddoc@0.0.1 dev
> astro dev

22:40:20 [starlight-obsidian-plugin] Generating Starlight pages from Obsidian vault…
22:40:21 [ERROR] [starlight-obsidian-plugin] URI malformed
[AstroUserError] Failed to generate Starlight pages from Obsidian vault.
  Hint:
    See the error report above for more informations.
    
    If you believe this is a bug, please file an issue at https://github.com/HiDeoo/starlight-obsidian/issues/new/choose
  Stack trace:
    at Module.throwUserError (C:/wa/vm/astro/MdDoc/node_modules/starlight-obsidian/libs/plugin.ts:6:9)
    at async Module.runPlugins (C:/wa/vm/astro/MdDoc/node_modules/@astrojs/starlight/utils/plugins.ts:26:5)
    at async withTakingALongTimeMsg (file:///C:/wa/vm/astro/MdDoc/node_modules/astro/dist/integrations/index.js:23:18)
    at async createContainer (file:///C:/wa/vm/astro/MdDoc/node_modules/astro/dist/core/dev/container.js:20:14)
    at async dev (file:///C:/wa/vm/astro/MdDoc/node_modules/astro/dist/core/dev/dev.js:14:19)

### Expected behavior

允许%出现在文件名中

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

This should now be fixed in version [`0.4.3`](https://github.com/HiDeoo/starlight-obsidian/releases/tag/v0.4.3) that I just released :tada:

**Comment by wangzilaing** [comment]
感谢您的辛苦工作！🙏🏼
